sudo: false
language: python
cache: pip
env:
  - TOXENV=py36
  - TOXENV=pypy
addons:
    apt:
        packages:
            - pypy-dev
            - liblapack-dev
install:
    - |
        if [[ "$TOXENV" = "pypy" ]]; then
            git clone https://github.com/yyuu/pyenv.git ~/.pyenv
            PYENV_ROOT="$HOME/.pyenv"
            PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init -)"
            pyenv install pypy3.5-6.0.0
            pyenv global pypy3.5-6.0.0
        fi
    - pip install tox-travis tox coveralls
script:
    - tox -e $TOXENV
after_success:
    - coveralls
