sudo: false
language: python
cache: pip
addons:
  apt_packages:
    - swig3.0
python:
  - "3.5"
  - "3.6"
install:
    - pip install tox tox-travis coveralls
script:
    - tox
after_success:
    - coveralls
